services:
  local.frp.server:
    build:
      context: .
      dockerfile: Dockerfile-frps
    image: frps:1.0
    ports:
      - 7500:7500
      - "2000-2020:2000-2020/tcp"
      - 0:22
    networks:
      - frp_network
    restart: always
  local.frp.client:
    build:
      context: .
      dockerfile: Dockerfile-frpc
    depends_on: 
      - local.frp.server
    image: frpc:1.0
    ports:
      - 0:22
      - 0:7400
    networks:
      - frp_network
    restart: always
volumes:
  frp_data:
networks:
  frp_network:
    driver: bridge

# docker compose -f docker-compose-frp.yml up --scale frp-client=5 --build
# https://github.com/fatedier/frp