FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'root:S1' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN mkdir /var/run/sshd
RUN mkdir /app

COPY ./frp_data/frps /app
COPY ./frp_data/frpc /app
COPY ./frp_data/frps.toml /app
COPY ./frp_data/frpc.toml /app
COPY ./startup_c.sh /tmp/startup_c.sh

RUN chmod +x /app/frps
RUN chmod +x /app/frpc
RUN chmod +x /tmp/startup_c.sh

WORKDIR /app
EXPOSE 22 7400 6000

CMD ["/tmp/startup_c.sh"]