FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'root:S1' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN mkdir /var/run/sshd
RUN mkdir /app

COPY ./frp_data/frps /app
COPY ./frp_data/frpc /app
COPY ./frp_data/frps.toml /app
COPY ./frp_data/frpc.toml /app
COPY ./startup_s.sh /tmp/startup_s.sh

RUN chmod +x /app/frps
RUN chmod +x /app/frpc
RUN chmod +x /tmp/startup_s.sh

WORKDIR /app
EXPOSE 2000-2020/tcp
EXPOSE 80 22 7500 7000

CMD ["/tmp/startup_s.sh"]