services:
#https://github.com/fatedier/frp#accessing-internal-web-services-with-custom-domains-in-lan
  local.frp.server:
    image: frps:1.0
    ports:
      - 7500:7500
      - "2000-2020:2000-2020/tcp"
      - 2202:22
    networks:
      - frp_network
    restart: always
  frp-client:
    depends_on: 
      - local.frp.server
    image: frpc:1.0
    ports:
      - 0:22
      - 0:7400
    networks:
      - frp_network
    restart: always
volumes:
  frp_data:
networks:
  frp_network:
    driver: bridge

# docker compose -f docker-compose-frp.yml up --scale frp-client=5