services:
  db:
    image: mysql:8.3.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  wordpress:
    image: wordpress:6.4.3-php8.3-apache
    volumes:
      - ${PWD}/wordpress_data_old:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wp_old
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  db_data:
  wordpress_data: